/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author visitante
 */
public class Mdi9959_22_2702 extends javax.swing.JFrame {

    /**
     * Creates new form MdiGeneral
     */
    public Mdi9959_22_2702() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(Mdi9959_22_2702.MAXIMIZED_BOTH);
        this.setTitle("Ejemplo Capas");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoAbrirSesion = new javax.swing.JMenuItem();
        mnuArchivoCerrarSesion = new javax.swing.JMenuItem();
        mnuCatalogos = new javax.swing.JMenu();
        mnuCatalogosMantenimiento = new javax.swing.JMenu();
        ManMoneda = new javax.swing.JMenuItem();
        mnuProcesos = new javax.swing.JMenu();
        mnuInformes = new javax.swing.JMenu();
        mnuHerramientas = new javax.swing.JMenu();
        mnuSeguridad = new javax.swing.JMenu();
        mnuSeguridadBitacora = new javax.swing.JMenuItem();
        mnuAyudas = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuArchivoAbrirSesion.setText("Abrir Sesion");
        mnuArchivoAbrirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoAbrirSesionActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoAbrirSesion);

        mnuArchivoCerrarSesion.setText("Cerrar Sesion");
        mnuArchivo.add(mnuArchivoCerrarSesion);

        jMenuBar1.add(mnuArchivo);

        mnuCatalogos.setText("Catalogos");

        mnuCatalogosMantenimiento.setText("Mantenimientos");
        mnuCatalogosMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientoActionPerformed(evt);
            }
        });

        ManMoneda.setText("Mantenimiento TipoDeMoneda");
        ManMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManMonedaActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimiento.add(ManMoneda);

        mnuCatalogos.add(mnuCatalogosMantenimiento);

        jMenuBar1.add(mnuCatalogos);

        mnuProcesos.setText("Procesos");
        mnuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcesosActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuProcesos);

        mnuInformes.setText("Informes");
        jMenuBar1.add(mnuInformes);

        mnuHerramientas.setText("Herramientas");

        mnuSeguridad.setText("Seguridad");

        mnuSeguridadBitacora.setText("Consulta Bitacora");
        mnuSeguridadBitacora.setName("mnuSeguridadBitacora"); // NOI18N
        mnuSeguridadBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSeguridadBitacoraActionPerformed(evt);
            }
        });
        mnuSeguridad.add(mnuSeguridadBitacora);

        mnuHerramientas.add(mnuSeguridad);

        jMenuBar1.add(mnuHerramientas);

        mnuAyudas.setText("Ayuda");
        jMenuBar1.add(mnuAyudas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCatalogosMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuCatalogosMantenimientoActionPerformed

    private void mnuArchivoAbrirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoAbrirSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuArchivoAbrirSesionActionPerformed

    private void mnuSeguridadBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSeguridadBitacoraActionPerformed
        // TODO add your handling code here:
        /*frmMantenimientoBitacora ventana = new frmMantenimientoBitacora();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);*/
    }//GEN-LAST:event_mnuSeguridadBitacoraActionPerformed

    private void ManMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManMonedaActionPerformed
        // TODO add your handling code here:
        /*MantenimientoTiposDeMoneda ventana = new MantenimientoTiposDeMoneda();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);*/
    }//GEN-LAST:event_ManMonedaActionPerformed

    private void mnuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcesosActionPerformed
        // TODO add your handling code here:
        /*ProcesoTesoreria ventana = new ProcesoTesoreria();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ventana.setVisible(true);*/
    }//GEN-LAST:event_mnuProcesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mdi9959_22_2702.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mdi9959_22_2702.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mdi9959_22_2702.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mdi9959_22_2702.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mdi9959_22_2702().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ManMoneda;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoAbrirSesion;
    private javax.swing.JMenuItem mnuArchivoCerrarSesion;
    private javax.swing.JMenu mnuAyudas;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuCatalogosMantenimiento;
    private javax.swing.JMenu mnuHerramientas;
    private javax.swing.JMenu mnuInformes;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenu mnuSeguridad;
    private javax.swing.JMenuItem mnuSeguridadBitacora;
    // End of variables declaration//GEN-END:variables
}
